import { HK2020_HEIGHT } from "../data/hk2020-height.js";
import { REFERENCE_INFO, calculateAgeFromDates, calculateGrowth, formatAge, formatPercentile, generateSameCentileTrajectory } from "./growth-engine.js";
import { loadState, saveState, exportState, importState, addRecord, removeRecord } from "./storage.js";

const state = loadState();
let chart;
let viewEndMonths = 216;
const focusedPercentiles = new Set(["p25", "p50", "p75"]);
const percentileStyles = {
  p25: { label: "P25", color: "#3d93a2" },
  p50: { label: "P50", color: "#176b87" },
  p75: { label: "P75", color: "#2f8796" }
};
const $ = (selector) => document.querySelector(selector);
const profile = () => state.profiles[state.currentProfileId];
const ageInMonths = (dob, date) => calculateAgeFromDates(dob, date).ageMonths;
const tableFor = () => HK2020_HEIGHT[profile().sex];
const currentReference = () => state.referenceStandard;

function getRecords() { return [...profile().records].sort((a, b) => a.date.localeCompare(b.date)); }
function render() { renderProfileTabs(); renderControls(); renderSummary(); renderChart(); renderHistory(); }
function formatProfileDate(value) { return new Intl.DateTimeFormat("zh-HK", { year: "numeric", month: "long", day: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)); }
function renderProfileTabs() { document.querySelectorAll(".profile-tab").forEach((button) => button.classList.toggle("active", button.dataset.profile === state.currentProfileId)); const details = [`生日：${formatProfileDate(profile().dateOfBirth)}`]; if (profile().expectedDateOfConfinement) details.push(`預產期：${formatProfileDate(profile().expectedDateOfConfinement)}`); $("#profile-meta").textContent = details.join(" · "); }
function renderControls() { $("#reference-select").value = currentReference(); $("#reference-badge").textContent = REFERENCE_INFO[currentReference()].label; document.querySelectorAll("[data-range]").forEach((button) => button.classList.toggle("active", Number(button.dataset.range) === viewEndMonths)); document.querySelectorAll("[data-percentile]").forEach((button) => button.setAttribute("aria-pressed", String(focusedPercentiles.has(button.dataset.percentile)))); }
function latestResult() { const records = getRecords(); if (!records.length) return null; const latest = records.at(-1); return { record: latest, result: calculateGrowth(latest.lengthHeightCm, ageInMonths(profile().dateOfBirth, latest.date), tableFor()) }; }
function latestTrajectory() { const latest = latestResult(); return latest ? generateSameCentileTrajectory({ measurement: latest.record.lengthHeightCm, ageMonths: latest.result.ageMonths }, tableFor()) : null; }
function renderSummary() { const latest = latestResult(); if (!latest) { ["#latest-height", "#latest-age", "#latest-percentile", "#latest-zscore", "#adult-reference"].forEach((selector) => $(selector).textContent = "—"); $("#adult-reference-note").textContent = "按量度時精確年齡投影 · 非醫療預測"; return; } const { record, result } = latest; const exactAge = calculateAgeFromDates(profile().dateOfBirth, record.date); $("#latest-height").textContent = `${record.lengthHeightCm.toFixed(1)} cm`; $("#latest-age").textContent = `${exactAge.label} · ${record.date}`; $("#latest-percentile").textContent = formatPercentile(result.percentile); $("#latest-zscore").textContent = `Z-score ${result.z.toFixed(2)}`; const adult = latestTrajectory()?.points.at(-1); $("#adult-reference").textContent = adult ? `${adult.y.toFixed(1)} cm` : "—"; $("#adult-reference-note").textContent = `按量度時 ${exactAge.label} 投影 · 非醫療預測`; }
function referenceDatasets() { const rows = tableFor(); const keys = [{ key: "p0_4", label: "P0.4" }, { key: "p2", label: "P2" }, { key: "p9", label: "P9" }, { key: "p25", label: "P25" }, { key: "p50", label: "P50" }, { key: "p75", label: "P75" }, { key: "p91", label: "P91" }, { key: "p98", label: "P98" }, { key: "p99_6", label: "P99.6" }]; return keys.map(({ key, label }) => { const focused = focusedPercentiles.has(key); const style = percentileStyles[key]; return { label, data: rows.map((row) => ({ x: row.ageMonths, y: row.centiles[key] })), borderColor: style?.color ?? "rgba(121,149,157,.26)", borderWidth: key === "p50" ? 2.4 : focused ? 2 : 1, pointRadius: 0, borderDash: key === "p50" ? [4, 3] : focused ? [6, 4] : [2, 4], tension: .22, order: 3, tooltip: focused, focusLabel: style?.label ?? null }; }); }
const focusLabelPlugin = { id: "focus-labels", afterDatasetsDraw(chartInstance) { const { ctx, chartArea } = chartInstance; const occupied = []; ctx.save(); ctx.font = "700 11px -apple-system, BlinkMacSystemFont, PingFang TC, sans-serif"; ctx.textAlign = "right"; ctx.textBaseline = "middle"; chartInstance.data.datasets.forEach((dataset, datasetIndex) => { if (!dataset.focusLabel) return; const meta = chartInstance.getDatasetMeta(datasetIndex); const point = meta.data.at(-1); if (!point) return; const props = point.getProps(["x", "y"], true); let y = props.y; while (occupied.some((usedY) => Math.abs(usedY - y) < 14)) y += 14; occupied.push(y); ctx.fillStyle = dataset.borderColor; ctx.fillText(dataset.focusLabel, chartArea.right - 5, y); }); ctx.restore(); } };
function renderChart() { const records = getRecords(); const actual = records.map((record) => ({ x: ageInMonths(profile().dateOfBirth, record.date), y: record.lengthHeightCm })); const latest = latestResult(); const projected = latest ? latestTrajectory()?.points ?? [] : []; const datasets = [...referenceDatasets(), { label: "實測記錄", data: actual, borderColor: "#176b87", backgroundColor: "#176b87", pointRadius: 5, pointHoverRadius: 7, borderWidth: 3, tension: .2, order: 1, tooltip: true }, { label: "同百分位參考軌跡", data: projected, borderColor: "#d65d60", backgroundColor: "#d65d60", pointRadius: 0, borderWidth: 2.5, borderDash: [7, 6], tension: .25, order: 2, tooltip: true }]; const ctx = $("#growth-chart"); if (chart) chart.destroy(); chart = new Chart(ctx, { type: "line", data: { datasets }, plugins: [focusLabelPlugin], options: { responsive: true, maintainAspectRatio: false, interaction: { mode: "x", intersect: false, axis: "x" }, plugins: { legend: { display: false }, tooltip: { mode: "x", intersect: false, filter: (item) => item.dataset.tooltip !== false, callbacks: { title: (items) => items.length ? formatAge(items[0].parsed.x) : "", label: (item) => `${item.dataset.label}: ${item.parsed.y.toFixed(1)} cm` } } }, scales: { x: { type: "linear", min: 0, max: viewEndMonths, title: { display: true, text: "年齡" }, ticks: { callback: (value) => `${Number(value) / 12}歲` }, grid: { color: "rgba(151,176,182,.16)" } }, y: { title: { display: true, text: "厘米" }, grid: { color: "rgba(151,176,182,.16)" } } } } }); }
function renderHistory() { const list = $("#history-list"); const records = getRecords().reverse(); if (!records.length) { list.innerHTML = '<div class="history-empty">尚未有量度記錄。</div>'; return; } list.replaceChildren(...records.map((record) => { const item = document.createElement("div"); item.className = "history-item"; const age = calculateAgeFromDates(profile().dateOfBirth, record.date); const result = calculateGrowth(record.lengthHeightCm, age.ageMonths, tableFor()); const main = document.createElement("div"); main.className = "history-main"; const title = document.createElement("strong"); title.textContent = `${record.date} · ${record.lengthHeightCm.toFixed(1)} cm`; const meta = document.createElement("span"); meta.textContent = `${age.label} · ${record.measurementMethod === "recumbent" ? "躺臥身長" : "站立身高"}`; main.append(title, meta); const percentile = document.createElement("span"); percentile.className = "history-percentile"; percentile.textContent = formatPercentile(result.percentile); const button = document.createElement("button"); button.className = "delete-button"; button.type = "button"; button.textContent = "刪除"; button.addEventListener("click", () => { if (!window.confirm("確定刪除此記錄？")) return; removeRecord(state, state.currentProfileId, record.id); saveState(state); render(); }); item.append(main, percentile, button); return item; })); }

function updateAgePreview() { try { const age = calculateAgeFromDates(profile().dateOfBirth, $("#record-date").value); $("#record-age-preview").textContent = `系統自動記錄年齡：${age.label}`; $("#record-method").value = age.ageMonths < 24 ? "recumbent" : "standing"; $("#form-error").textContent = ""; } catch (error) { $("#record-age-preview").textContent = "系統會按生日自動計算年齡"; $("#form-error").textContent = error.message; } }
function openDialog() { const dialog = $("#record-dialog"); $("#record-date").value = new Date().toISOString().slice(0, 10); $("#record-height").value = ""; $("#record-weight").value = ""; $("#record-head").value = ""; $("#record-notes").value = ""; $("#form-error").textContent = ""; updateAgePreview(); if (typeof dialog.showModal === "function") dialog.showModal(); else dialog.setAttribute("open", ""); }
function closeDialog() { const dialog = $("#record-dialog"); if (typeof dialog.close === "function") dialog.close(); else dialog.removeAttribute("open"); }
$("#add-record-button").addEventListener("click", openDialog); $("#cancel-dialog").addEventListener("click", closeDialog); $("#close-dialog").addEventListener("click", closeDialog);
$("#record-date").addEventListener("change", updateAgePreview);
$("#record-form").addEventListener("submit", (event) => { event.preventDefault(); try { addRecord(state, state.currentProfileId, { date: $("#record-date").value, lengthHeightCm: $("#record-height").value, measurementMethod: $("#record-method").value, weightKg: $("#record-weight").value || null, headCircumferenceCm: $("#record-head").value || null, notes: $("#record-notes").value }); saveState(state); closeDialog(); render(); } catch (error) { $("#form-error").textContent = error.message; } });
document.querySelectorAll(".profile-tab").forEach((button) => button.addEventListener("click", () => { state.currentProfileId = button.dataset.profile; saveState(state); render(); })); document.querySelectorAll("[data-range]").forEach((button) => button.addEventListener("click", () => { viewEndMonths = Number(button.dataset.range); render(); })); $("#reference-select").addEventListener("change", (event) => { state.referenceStandard = event.target.value; saveState(state); render(); }); $("#export-button").addEventListener("click", () => exportState(state)); $("#import-button").addEventListener("click", () => $("#import-input").click()); $("#import-input").addEventListener("change", async (event) => { const file = event.target.files?.[0]; if (!file) return; try { const imported = importState(await file.text()); Object.assign(state, imported); saveState(state); render(); window.alert("備份已匯入。"); } catch (error) { window.alert(`匯入失敗：${error.message}`); } event.target.value = ""; });
document.querySelectorAll("[data-percentile]").forEach((button) => button.addEventListener("click", () => { const key = button.dataset.percentile; if (focusedPercentiles.has(key) && focusedPercentiles.size === 1) return; if (focusedPercentiles.has(key)) focusedPercentiles.delete(key); else focusedPercentiles.add(key); render(); }));
if ("serviceWorker" in navigator) window.addEventListener("load", () => navigator.serviceWorker.register("./sw.js").catch(() => {}));
render();
